services:
  postgres:
    image: postgres:16-alpine
    container_name: carcar_dev_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Esmeralda14
      POSTGRES_DB: carcar_local
    ports:
      - "5435:5432"
    volumes:
      - carcar_dev_pgdata:/var/lib/postgresql/data

volumes:
  carcar_dev_pgdata:
